In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [4]:
df = pd.read_csv("ChurnData.csv")

In [5]:
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [6]:
df.describe()

tenure         age     address       income         ed     employ  \
count  200.000000  200.000000  200.000000   200.000000  200.00000  200.00000   
mean    35.505000   41.165000   11.650000    75.130000    2.82500   10.22500   
std     21.640971   13.076803   10.158419   128.430468    1.28555    8.95743   
min      1.000000   19.000000    0.000000     9.000000    1.00000    0.00000   
25%     16.750000   31.000000    3.000000    31.000000    2.00000    3.00000   
50%     33.500000   40.000000    9.000000    48.000000    3.00000    7.50000   
75%     55.250000   51.000000   18.000000    80.000000    4.00000   17.00000   
max     72.000000   76.000000   48.000000  1668.000000    5.00000   44.00000   

            equip    callcard    wireless    longmon  ...       pager  \
count  200.000000  200.000000  200.000000  200.00000  ...  200.000000   
mean     0.425000    0.705000    0.290000   11.78925  ...    0.275000   
std      0.495584    0.457187    0.454901    9.88725  ...    0.447635   
min      0.000000    0.000000    0.000000    1.10000  ...    0.000000   
25%      0.000000    0.000000    0.000000    5.53750  ...    0.000000   
50%      0.000000    1.000000    0.000000    8.25000  ...    0.000000   
75%      1.000000    1.000000    1.000000   14.30000  ...    1.000000   
max      1.000000    1.000000    1.000000   62.30000  ...    1.000000   

         internet   callwait      confer       ebill     loglong     logtoll  \
count  200.000000  200.00000  200.000000  200.000000  200.000000  200.000000   
mean     0.440000    0.45500    0.460000    0.440000    2.193285    3.229185   
std      0.497633    0.49922    0.499648    0.497633    0.731282    0.281019   
min      0.000000    0.00000    0.000000    0.000000    0.095000    1.749000   
25%      0.000000    0.00000    0.000000    0.000000    1.711750    3.226500   
50%      0.000000    0.00000    0.000000    0.000000    2.110000    3.240000   
75%      1.000000    1.00000    1.000000    1.000000    2.660000    3.240000   
max      1.000000    1.00000    1.000000    1.000000    4.132000    4.227000   

            lninc     custcat       churn  
count  200.000000  200.000000  200.000000  
mean     3.951015    2.475000    0.290000  
std      0.752553    1.079445    0.454901  
min      2.197000    1.000000    0.000000  
25%      3.434000    2.000000    0.000000  
50%      3.871000    2.000000    0.000000  
75%      4.382000    3.000000    1.000000  
max      7.419000    4.000000    1.000000  

[8 rows x 28 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 28 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   tenure    200 non-null    float64
 1   age       200 non-null    float64
 2   address   200 non-null    float64
 3   income    200 non-null    float64
 4   ed        200 non-null    float64
 5   employ    200 non-null    float64
 6   equip     200 non-null    float64
 7   callcard  200 non-null    float64
 8   wireless  200 non-null    float64
 9   longmon   200 non-null    float64
 10  tollmon   200 non-null    float64
 11  equipmon  200 non-null    float64
 12  cardmon   200 non-null    float64
 13  wiremon   200 non-null    float64
 14  longten   200 non-null    float64
 15  tollten   200 non-null    float64
 16  cardten   200 non-null    float64
 17  voice     200 non-null    float64
 18  pager     200 non-null    float64
 19  internet  200 non-null    float64
 20  callwait  200 non-null    float6

In [8]:
# Applying Variance

In [9]:
from sklearn.feature_selection import VarianceThreshold

In [10]:
vart = VarianceThreshold()

In [11]:
op = vart.fit(df)

In [12]:
op.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [13]:
df.columns[op.get_support()==True]

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon', 'cardmon',
       'wiremon', 'longten', 'tollten', 'cardten', 'voice', 'pager',
       'internet', 'callwait', 'confer', 'ebill', 'loglong', 'logtoll',
       'lninc', 'custcat', 'churn'],
      dtype='object')

In [14]:
vart2 = VarianceThreshold(threshold=0.5)

In [15]:
op = vart2.fit(df)

In [16]:
op.get_support()

array([ True,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False,  True, False,  True,  True,
       False])

In [17]:
df.columns[op.get_support()==True]

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'longmon',
       'tollmon', 'equipmon', 'cardmon', 'wiremon', 'longten', 'tollten',
       'cardten', 'loglong', 'lninc', 'custcat'],
      dtype='object')

In [18]:
c_names = df.columns[op.get_support()==False]
c_names

Index(['equip', 'callcard', 'wireless', 'voice', 'pager', 'internet',
       'callwait', 'confer', 'ebill', 'logtoll', 'churn'],
      dtype='object')

In [19]:
cdf = df['churn'] # Storing DV in cdf dataframe

In [20]:
df.drop(c_names, axis=1, inplace=True)

In [21]:
df.head()

tenure   age  address  income   ed  employ  longmon  tollmon  equipmon  \
0    11.0  33.0      7.0   136.0  5.0     5.0     4.40    20.75       0.0   
1    33.0  33.0     12.0    33.0  2.0     0.0     9.45     0.00       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0     6.30     0.00       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0     6.05    45.00      50.1   
4     7.0  35.0     14.0    80.0  2.0    15.0     7.10    22.00       0.0   

   cardmon  wiremon  longten  tollten  cardten  loglong  lninc  custcat  
0    15.25     35.7    42.00   211.45    125.0    1.482  4.913      4.0  
1     0.00      0.0   288.80     0.00      0.0    2.246  3.497      1.0  
2     0.00      0.0   157.05     0.00      0.0    1.841  3.401      3.0  
3    23.25     64.9   239.55  1873.05    880.0    1.800  4.331      4.0  
4    23.75      0.0    47.45   166.10    145.0    1.960  4.382      3.0

In [22]:
# Applying MIC

In [23]:
from sklearn.feature_selection import mutual_info_classif

In [24]:
MIC = mutual_info_classif(df, cdf)

In [25]:
MIC

array([0.1311906 , 0.02496618, 0.04858503, 0.03508064, 0.0541206 ,
       0.07489259, 0.03126277, 0.04274667, 0.03229822, 0.00036868,
       0.08168195, 0.05729314, 0.03693939, 0.08581942, 0.02475521,
       0.02288208, 0.        ])

In [26]:
mic_ser = pd.Series(MIC)

In [27]:
mic_ser

0     0.131191
1     0.024966
2     0.048585
3     0.035081
4     0.054121
5     0.074893
6     0.031263
7     0.042747
8     0.032298
9     0.000369
10    0.081682
11    0.057293
12    0.036939
13    0.085819
14    0.024755
15    0.022882
16    0.000000
dtype: float64

In [28]:
columnames = df.columns
columnames

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'longmon',
       'tollmon', 'equipmon', 'cardmon', 'wiremon', 'longten', 'tollten',
       'cardten', 'loglong', 'lninc', 'custcat'],
      dtype='object')

In [29]:
mic_ser.index = columnames
mic_ser

tenure      0.131191
age         0.024966
address     0.048585
income      0.035081
ed          0.054121
employ      0.074893
longmon     0.031263
tollmon     0.042747
equipmon    0.032298
cardmon     0.000369
wiremon     0.081682
longten     0.057293
tollten     0.036939
cardten     0.085819
loglong     0.024755
lninc       0.022882
custcat     0.000000
dtype: float64

In [30]:
mic_ser.sort_values(ascending=False)

tenure      0.131191
cardten     0.085819
wiremon     0.081682
employ      0.074893
longten     0.057293
ed          0.054121
address     0.048585
tollmon     0.042747
tollten     0.036939
income      0.035081
equipmon    0.032298
longmon     0.031263
age         0.024966
loglong     0.024755
lninc       0.022882
cardmon     0.000369
custcat     0.000000
dtype: float64

In [31]:
removable_col = []
for i in mic_ser.index:
    if mic_ser[i] < 0.02:
        print(i, mic_ser[i])
        removable_col.append(i)

cardmon 0.0003686769430659709
custcat 0.0


In [32]:
df.drop(removable_col, axis=1, inplace=True)

In [33]:
df.head()

tenure   age  address  income   ed  employ  longmon  tollmon  equipmon  \
0    11.0  33.0      7.0   136.0  5.0     5.0     4.40    20.75       0.0   
1    33.0  33.0     12.0    33.0  2.0     0.0     9.45     0.00       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0     6.30     0.00       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0     6.05    45.00      50.1   
4     7.0  35.0     14.0    80.0  2.0    15.0     7.10    22.00       0.0   

   wiremon  longten  tollten  cardten  loglong  lninc  
0     35.7    42.00   211.45    125.0    1.482  4.913  
1      0.0   288.80     0.00      0.0    2.246  3.497  
2      0.0   157.05     0.00      0.0    1.841  3.401  
3     64.9   239.55  1873.05    880.0    1.800  4.331  
4      0.0    47.45   166.10    145.0    1.960  4.382

In [34]:
# Creating model with Logistic Regression

In [35]:
cdf = cdf.astype('int')

In [36]:
x = np.asarray(df)

In [37]:
x[0:5]

array([[1.10000e+01, 3.30000e+01, 7.00000e+00, 1.36000e+02, 5.00000e+00,
        5.00000e+00, 4.40000e+00, 2.07500e+01, 0.00000e+00, 3.57000e+01,
        4.20000e+01, 2.11450e+02, 1.25000e+02, 1.48200e+00, 4.91300e+00],
       [3.30000e+01, 3.30000e+01, 1.20000e+01, 3.30000e+01, 2.00000e+00,
        0.00000e+00, 9.45000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        2.88800e+02, 0.00000e+00, 0.00000e+00, 2.24600e+00, 3.49700e+00],
       [2.30000e+01, 3.00000e+01, 9.00000e+00, 3.00000e+01, 1.00000e+00,
        2.00000e+00, 6.30000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        1.57050e+02, 0.00000e+00, 0.00000e+00, 1.84100e+00, 3.40100e+00],
       [3.80000e+01, 3.50000e+01, 5.00000e+00, 7.60000e+01, 2.00000e+00,
        1.00000e+01, 6.05000e+00, 4.50000e+01, 5.01000e+01, 6.49000e+01,
        2.39550e+02, 1.87305e+03, 8.80000e+02, 1.80000e+00, 4.33100e+00],
       [7.00000e+00, 3.50000e+01, 1.40000e+01, 8.00000e+01, 2.00000e+00,
        1.50000e+01, 7.10000e+00, 2.20000e+01, 

In [38]:
y = np.asarray(cdf)

In [39]:
y[0:5]

array([1, 1, 0, 0, 0])

In [40]:
from sklearn import preprocessing

In [41]:
x = preprocessing.StandardScaler().fit(x).transform(x)

In [42]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 156)

In [43]:
print("Train status", x_train.shape, y_train.shape)
print("Test status", x_test.shape, y_test.shape)

Train status (160, 15) (160,)
Test status (40, 15) (40,)


In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
LR = LogisticRegression (C=0.2, solver = "newton-cg", verbose=1).fit(x_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


In [46]:
y_pred = LR.predict(x_test)

In [47]:
from sklearn.metrics import accuracy_score as acc

In [48]:
print(acc(y_test, y_pred)*100)

77.5


In [49]:
import pickle
pickle.dump(LR, open('model.pkl', 'wb'))